name: Autoformat code

on:
    push:
      branches: [ 'main' ]
    pull_request:
      branches: [ 'main' ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code
        run: |
          pip install black
          black .
      - name: Sort imports
        run: |
          pip install isort
          isort .
      - name: Remove unused imports
        run: |
          pip install autoflake
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Autoformat code"
          add: "."
          branch: ${{ github.ref }}